---
title: "Assignment_10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Question 1 
```{r}
library(ggplot2)
counter<-0

count<-function(n, size, prob){
x<-rbinom(n = n, size = size, prob = prob)
for(i in 1:n){
  if (x[i]==0) {
    counter<-counter+1
  }
}
return(counter)
}

count(1000, 3, 0.5)


```

### Question 2

```{r}
count<-function(n, size, prob){
  x<-rbinom(n = n, size = size, prob = prob)
 counter<-NROW(x[which(x[1:n]==0)])
 return(counter)
}

count(2000, 4, 0.5)

```

### Question 3
```{r}
matfunc<-function(row, col){
mat<-matrix(nrow = row, ncol=col)
for(i in 1:row){
  for(j in 1:col){
    mat[i,j]<-i*j
  }
}
return(mat)
}

matfunc(2, 4)
```


### Question 4
```{r}
set.seed(0)
fiola<-read.csv("fiola.csv")
fiola$ID<-1:53
myData<-data.frame(ID=fiola$ID, xObs=fiola$mean.seedling.density, yObs=fiola$mean.chipmunk.detections)

####### ###########################################
# function: readData
# read in (or generate) data set for analysis
# input: file name (or nothing, for this demo)
# output: 3 column data frame of observed data (ID,x,y)
#------------------------------------------------- 
readData <- function(z=NULL) {
  if(is.null(z)){
    xObs <- 1:20
    yObs <- xObs + 10*rnorm(20)
    dF <- myData} # set up data frame      
  
  #  dF <-read.table(file=z,row.names=1,header=TRUE,sep=",",stringsAsFactors=FALSE)
  # print(qplot(x=xObs,y=yObs)) # peek at input data
  return(dF)
}


##################################################
# function: getMetric
# calculate metric for randomization test
# input: 2-column data frame for regression
# output: regression slope
#------------------------------------------------- 
getMetric <- function(z=myData) {
  if(is.null(z)){
    xObs <- 1:20
    yObs <-  xObs + 10*rnorm(20)
    z <- data.frame(ID=seq_along(xObs),xObs,yObs)} # set up data frame                 
  . <- lm(z[,3]~z[,2])
  . <- summary(.)
  . <- .$coefficients[2,1]
  
  slope <- .
  return(slope)
}


##################################################
# function: shuffleData
# randomize data for regression analysis
# input: 3-column data frame (ID,xVar,yVar)
# output: 3-column data frame (ID,xVar,yVar)
#------------------------------------------------- 
shuffleData <- function(z) {
  if(is.null(z)){
    xObs <- 1:20
    yObs <- xObs + 3*rnorm(20)
    z <- data.frame(ID=seq_along(xObs),xObs,yObs)} # set up data frame                 
  z[,3] <- sample(z[,3]) # use sample function with defaults to reshuffle column
  
  return(z)
}

##################################################
# function: getPVal
# calculate p value from simulation
# input: list of observed metric, and vector of simulated metrics
# output: lower, upper tail probability values
#------------------------------------------------- 
getPVal <- function(z) {
  if(is.null(z)){
    z <- list(xObs=runif(1),xSim=runif(1000))}
  pLower <- mean(z[[2]]<=z[[1]])
  pUpper <- mean(z[[2]]>=z[[1]])
  return(c(pL=pLower,pU=pUpper))
}


#First get means of data 

##################################################
# function: plotRanTest
# create ggplot of histogram of simulated values
# input: list of observed metric and vector of simulated metrics
# output: saved ggplot graph
#------------------------------------------------- 
plotRanTest <- function(z=myData) {
  if(is.null(z)){
    z <- list(rnorm(1),rnorm(1000)) }
  
  dF <- data.frame(ID=seq_along(z[[2]]),simX=z[[2]])
  p1 <- ggplot(data=dF,mapping=aes(x=simX))
  p1 + geom_histogram(mapping=aes(fill=I("goldenrod"),color=I("black"))) +
    geom_vline(aes(xintercept=z[[1]],col="blue")) 
  
}
set.seed(1000)
nSim <- 100000
Xsim <- rep(NA,nSim) # vector of simulated slopes
dF <- readData()
Xobs <- getMetric()


for (i in seq_len(nSim)) {
  Xsim[i] <- getMetric(shuffleData(myData))
}

slopes <- list(Xobs,Xsim)

getPVal(slopes)


plotRanTest(slopes)

linmod<-lm(data = myData, formula= yObs~xObs)
summary(linmod)

```

Comparing the p-values, the pL from the simulated data is close to 1, indicating that all of the simulated p-values were greater, which does not match the results found if you were to conduct a standard linear regression model and find the p-value that way. 
